### ISSUE TITLE
Why not to host dll-s on nuget?

### ISSUE THREAD

**Issue by Cynede** [rneatherway/emacs-fsharp-mode-bin#1]
Or somewhere else... It will be good in case they will be periodically change.

**Comment by rneatherway** [comment]
I want to release this mode via melpa. The easiest way I know of is to have a github repository to build the package from. It's probably a good idea to make a nuget package for fsautocomplete.exe, I think the others are already on nuget.

**Comment by rneatherway** [comment]
Sorry but this isn't on my plan.
